restart-docker-compose:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Run remote script with SSH
        uses: appleboy/ssh-action@v1.0.3
        host: ${{ secrets.ADDRESS }}
        username: ${{ secrets.NAME }}
        key: ${{ secrets.CLOUD }}
        script: restart_docker_compose
